// This file is auto-generated by game/scripts/generateAssetManifest.mjs
// Do not edit manually. Re-run `npm run assets:manifest` after asset changes.

export type RuntimeAssetStage = 'critical' | 'static' | 'gif';

export type RuntimeAssetManifestEntry = {
  path: string;
  bytes: number;
  stage: RuntimeAssetStage;
};

export const RUNTIME_ASSET_MANIFEST: RuntimeAssetManifestEntry[] = [
  {
    "path": "/assets/background_main_menu.png",
    "bytes": 184108,
    "stage": "critical"
  },
  {
    "path": "/assets/constitutions/balanced.webp",
    "bytes": 42414,
    "stage": "critical"
  },
  {
    "path": "/assets/constitutions/qi_deficiency.webp",
    "bytes": 62658,
    "stage": "critical"
  },
  {
    "path": "/assets/constitutions/yin_deficiency.webp",
    "bytes": 52800,
    "stage": "critical"
  },
  {
    "path": "/assets/author_qr/ren-xuanqi.jpg",
    "bytes": 117281,
    "stage": "static"
  },
  {
    "path": "/assets/author_qr/wang-yi.jpg",
    "bytes": 165234,
    "stage": "static"
  },
  {
    "path": "/assets/background_map_act1.png",
    "bytes": 194750,
    "stage": "static"
  },
  {
    "path": "/assets/background_map_act2.webp",
    "bytes": 191618,
    "stage": "static"
  },
  {
    "path": "/assets/background_rest_act2.jpg",
    "bytes": 156726,
    "stage": "static"
  },
  {
    "path": "/assets/background_rest.png",
    "bytes": 189650,
    "stage": "static"
  },
  {
    "path": "/assets/background_shop.png",
    "bytes": 199205,
    "stage": "static"
  },
  {
    "path": "/assets/bg_synthesis_1.png",
    "bytes": 203055,
    "stage": "static"
  },
  {
    "path": "/assets/bg_synthesis_2.png",
    "bytes": 161350,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/100-poster.png",
    "bytes": 146869,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/100.png",
    "bytes": 83343,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/101-poster.png",
    "bytes": 104461,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/101.png",
    "bytes": 66065,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/102-poster.png",
    "bytes": 159885,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/102.png",
    "bytes": 96977,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/103-poster.png",
    "bytes": 156922,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/103.png",
    "bytes": 96680,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/104-poster.png",
    "bytes": 160588,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/76.png",
    "bytes": 3286,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/77.png",
    "bytes": 3378,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/78.png",
    "bytes": 3838,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/79-poster.png",
    "bytes": 151738,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/79.png",
    "bytes": 82734,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/80-poster.png",
    "bytes": 113281,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/80.png",
    "bytes": 75091,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/81.png",
    "bytes": 3670,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/82.png",
    "bytes": 3858,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/83-poster.png",
    "bytes": 131397,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/83.png",
    "bytes": 90921,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/84-poster.png",
    "bytes": 148584,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/84.png",
    "bytes": 104867,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/85.png",
    "bytes": 3519,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/89-poster.png",
    "bytes": 153443,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/89.png",
    "bytes": 99687,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/90-poster.png",
    "bytes": 139206,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/90.png",
    "bytes": 79130,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/91-poster.png",
    "bytes": 102629,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/91.png",
    "bytes": 86023,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/92-poster.png",
    "bytes": 190516,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/92.png",
    "bytes": 112264,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/93-poster.png",
    "bytes": 128220,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/93.png",
    "bytes": 74927,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/94-poster.png",
    "bytes": 145456,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/94.png",
    "bytes": 92809,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/95-poster.png",
    "bytes": 198463,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/95.png",
    "bytes": 127450,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/96-poster.png",
    "bytes": 139865,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/96.png",
    "bytes": 87558,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/97-poster.png",
    "bytes": 196806,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/97.png",
    "bytes": 122609,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/98-poster.png",
    "bytes": 125010,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/98.png",
    "bytes": 71020,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/99-poster.png",
    "bytes": 159724,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/99.png",
    "bytes": 103079,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/bianzheng.webp",
    "bytes": 98072,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/jingluo.webp",
    "bytes": 176220,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/qiji.webp",
    "bytes": 153420,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/qixue_jinye.webp",
    "bytes": 48596,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/tianren.webp",
    "bytes": 116312,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/yinyang.webp",
    "bytes": 73134,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/zangxiang.webp",
    "bytes": 201884,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/zhengti.webp",
    "bytes": 54808,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/zhengxie.webp",
    "bytes": 39370,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/zhiweibing.webp",
    "bytes": 91188,
    "stage": "static"
  },
  {
    "path": "/assets/cards_equipment/ziwuliuzhu.webp",
    "bytes": 131700,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/banxia_houpu_tang.png",
    "bytes": 53159,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/gegen_tang.png",
    "bytes": 57115,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/jiaotai_wan.png",
    "bytes": 56975,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/lizhong_wan.png",
    "bytes": 60204,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/mahuang_tang.png",
    "bytes": 45077,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/maxing_shigan_tang.png",
    "bytes": 68129,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/sijunzi_tang.png",
    "bytes": 56473,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/suanzaoren_tang.png",
    "bytes": 76440,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/xiaochaihu_tang.png",
    "bytes": 44157,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/xiaoqinglong_tang.png",
    "bytes": 76404,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/yinqiao_san.png",
    "bytes": 52506,
    "stage": "static"
  },
  {
    "path": "/assets/cards_formula_placeholders/zhenwu_tang.png",
    "bytes": 57586,
    "stage": "static"
  },
  {
    "path": "/assets/cards_herb_placeholders/huangqin.png",
    "bytes": 36388,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/1.png",
    "bytes": 72368,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/10.png",
    "bytes": 64048,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/11.png",
    "bytes": 48403,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/12.png",
    "bytes": 57877,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/13.png",
    "bytes": 68960,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/14.png",
    "bytes": 73522,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/15.png",
    "bytes": 81012,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/16.png",
    "bytes": 49231,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/17.png",
    "bytes": 41119,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/18.png",
    "bytes": 36893,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/19.png",
    "bytes": 68169,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/2.png",
    "bytes": 43278,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/20.png",
    "bytes": 87465,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/21.png",
    "bytes": 61805,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/22.png",
    "bytes": 76202,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/23.png",
    "bytes": 50541,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/24.png",
    "bytes": 21909,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/25.png",
    "bytes": 27307,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/26.png",
    "bytes": 49625,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/27.png",
    "bytes": 75995,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/28.png",
    "bytes": 24993,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/29.png",
    "bytes": 76187,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/3.png",
    "bytes": 48239,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/30.png",
    "bytes": 56826,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/31.png",
    "bytes": 70217,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/32.png",
    "bytes": 58766,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/33.png",
    "bytes": 67079,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/34.png",
    "bytes": 56756,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/35.png",
    "bytes": 62556,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/36.png",
    "bytes": 71566,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/38.png",
    "bytes": 55578,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/39.png",
    "bytes": 51270,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/4.png",
    "bytes": 28694,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/40.png",
    "bytes": 63799,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/41.png",
    "bytes": 52511,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/42.png",
    "bytes": 52988,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/43.png",
    "bytes": 50137,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/44.png",
    "bytes": 50074,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/45.png",
    "bytes": 45374,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/46.png",
    "bytes": 58740,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/47.png",
    "bytes": 71450,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/48.png",
    "bytes": 48131,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/49.png",
    "bytes": 71270,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/5.png",
    "bytes": 63539,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/50.png",
    "bytes": 76721,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/51.png",
    "bytes": 68797,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/52.png",
    "bytes": 75537,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/53.png",
    "bytes": 71560,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/54.png",
    "bytes": 104598,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/55.png",
    "bytes": 71595,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/56.png",
    "bytes": 79559,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/57.png",
    "bytes": 66737,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/58.png",
    "bytes": 64495,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/59.png",
    "bytes": 80979,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/6.png",
    "bytes": 32455,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/60.png",
    "bytes": 67963,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/61.png",
    "bytes": 67731,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/62.png",
    "bytes": 81541,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/63.png",
    "bytes": 88980,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/64.png",
    "bytes": 81193,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/65.png",
    "bytes": 68886,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/66.png",
    "bytes": 39368,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/67.png",
    "bytes": 53858,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/68.png",
    "bytes": 46293,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/69.png",
    "bytes": 37176,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/7.png",
    "bytes": 35730,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/70.png",
    "bytes": 43682,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/71.png",
    "bytes": 44010,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/72.png",
    "bytes": 33091,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/73.png",
    "bytes": 46192,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/74.png",
    "bytes": 35503,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/75.png",
    "bytes": 50471,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/76.png",
    "bytes": 92809,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/77.png",
    "bytes": 103079,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/78.png",
    "bytes": 74927,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/79.png",
    "bytes": 82734,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/8.png",
    "bytes": 50588,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/80.png",
    "bytes": 75091,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/81.png",
    "bytes": 127450,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/82.png",
    "bytes": 122609,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/83.png",
    "bytes": 90921,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/84.png",
    "bytes": 104867,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/85.png",
    "bytes": 66065,
    "stage": "static"
  },
  {
    "path": "/assets/cards_player/9.png",
    "bytes": 62975,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/angong.png",
    "bytes": 44699,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/angong.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/banxia.png",
    "bytes": 33823,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/banxia.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/baohe.png",
    "bytes": 36778,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/baohe.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/buzhongyiqi.png",
    "bytes": 50928,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/buzhongyiqi.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/chuanxiongcha.png",
    "bytes": 33053,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/chuanxiongcha.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/dachengqi.png",
    "bytes": 42968,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/dachengqi.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/danshen.png",
    "bytes": 32940,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/danshen.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/guipi.png",
    "bytes": 26924,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/guipi.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/huanglianjiedu.png",
    "bytes": 52165,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/huanglianjiedu.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/huoxiang.png",
    "bytes": 46372,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/huoxiang.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/jinkui.png",
    "bytes": 60011,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/jinkui.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/liuwei.png",
    "bytes": 63564,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/liuwei.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/longdan.png",
    "bytes": 40682,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/longdan.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/mahuangtang.png",
    "bytes": 42168,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/mahuangtang.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/qinggusan.png",
    "bytes": 56258,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/qinggusan.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/qingying.png",
    "bytes": 27711,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/qingying.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/sijunzi.png",
    "bytes": 42590,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/sijunzi.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/wumei.png",
    "bytes": 48646,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/wumei.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/xiaochaihu.png",
    "bytes": 43076,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/xiaochaihu.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/xiaoyao.png",
    "bytes": 21356,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/xiaoyao.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/xuefu.png",
    "bytes": 35923,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/xuefu.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/yinqiao.png",
    "bytes": 31540,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/yinqiao.svg",
    "bytes": 1816,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/yupingfeng.png",
    "bytes": 53938,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/yupingfeng.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/zhenwu.png",
    "bytes": 49209,
    "stage": "static"
  },
  {
    "path": "/assets/cards_replacement_placeholders/zhenwu.svg",
    "bytes": 1814,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/act_frame.png",
    "bytes": 4135,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/back_map_button.png",
    "bytes": 8448,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/background_act2.webp",
    "bytes": 203324,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/background.webp",
    "bytes": 99794,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/combat_log_panel.png",
    "bytes": 57996,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/deck_frame_icon.png",
    "bytes": 6556,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/discard_frame_icon.png",
    "bytes": 6157,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/divider_line.png",
    "bytes": 345,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/draw_frame_icon.png",
    "bytes": 6710,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/draw_per_turn_frame_icon.png",
    "bytes": 2020,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/end_turn_button.png",
    "bytes": 33981,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/equipment_icon.png",
    "bytes": 2336,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/equipment_tab_frame.png",
    "bytes": 6330,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/gold_frame_icon.png",
    "bytes": 7332,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/green_bar.png",
    "bytes": 1310,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/hand_frame_icon.png",
    "bytes": 2508,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/hp_bar_frame.png",
    "bytes": 13515,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/hp_icon.png",
    "bytes": 5731,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/intent_icon.png",
    "bytes": 3195,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/passive_panel.png",
    "bytes": 52512,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/passive_tab_frame.png",
    "bytes": 2518,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/passive_unselected_marker.png",
    "bytes": 1354,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/pathogen_icon.png",
    "bytes": 3149,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/player_health_panel.png",
    "bytes": 37144,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/player_resource_panel.png",
    "bytes": 43261,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/qi_icon.png",
    "bytes": 6966,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/red_bar.png",
    "bytes": 7387,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/status_icon_1.png",
    "bytes": 5328,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/status_icon_2.png",
    "bytes": 4789,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/status_icon_3.png",
    "bytes": 5470,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/turn_player_frame.png",
    "bytes": 4219,
    "stage": "static"
  },
  {
    "path": "/assets/combat/v2/turn_resource_frame.png",
    "bytes": 4049,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/back_to_menu.png",
    "bytes": 11686,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/background.png",
    "bytes": 328205,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/choice_button_frame.png",
    "bytes": 6075,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/deck_icon.png",
    "bytes": 67595,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/hover_frame.png",
    "bytes": 25676,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/page_controls_hover.png",
    "bytes": 5384,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/page_left.png",
    "bytes": 3509,
    "stage": "static"
  },
  {
    "path": "/assets/constitution_select/page_right.png",
    "bytes": 3535,
    "stage": "static"
  },
  {
    "path": "/assets/constitutions/blood_stasis.webp",
    "bytes": 63208,
    "stage": "static"
  },
  {
    "path": "/assets/constitutions/damp_heat.webp",
    "bytes": 116864,
    "stage": "static"
  },
  {
    "path": "/assets/constitutions/phlegm_dampness.webp",
    "bytes": 68668,
    "stage": "static"
  },
  {
    "path": "/assets/constitutions/qi_stagnation.webp",
    "bytes": 51690,
    "stage": "static"
  },
  {
    "path": "/assets/constitutions/special_diathesis.webp",
    "bytes": 103954,
    "stage": "static"
  },
  {
    "path": "/assets/constitutions/yang_deficiency.webp",
    "bytes": 67524,
    "stage": "static"
  },
  {
    "path": "/assets/intro/agreement.png",
    "bytes": 6224,
    "stage": "static"
  },
  {
    "path": "/assets/intro/background.webp",
    "bytes": 209500,
    "stage": "static"
  },
  {
    "path": "/assets/intro/enter_main_menu.png",
    "bytes": 50967,
    "stage": "static"
  },
  {
    "path": "/assets/intro/icon_activity.png",
    "bytes": 15104,
    "stage": "static"
  },
  {
    "path": "/assets/intro/icon_codex.png",
    "bytes": 13246,
    "stage": "static"
  },
  {
    "path": "/assets/intro/icon_frame.png",
    "bytes": 6605,
    "stage": "static"
  },
  {
    "path": "/assets/intro/icon_notice.png",
    "bytes": 13060,
    "stage": "static"
  },
  {
    "path": "/assets/intro/icon_settings.png",
    "bytes": 13634,
    "stage": "static"
  },
  {
    "path": "/assets/intro/side_menu.png",
    "bytes": 61393,
    "stage": "static"
  },
  {
    "path": "/assets/intro/title.png",
    "bytes": 167249,
    "stage": "static"
  },
  {
    "path": "/assets/intro/top_copy.png",
    "bytes": 28190,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/background.webp",
    "bytes": 82496,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/admin_icon.png",
    "bytes": 3732,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/admin_plate.png",
    "bytes": 86570,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/admin_text.png",
    "bytes": 7296,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/border.png",
    "bytes": 2407,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/codex_icon.png",
    "bytes": 3671,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/codex_plate.png",
    "bytes": 90457,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/codex_text.png",
    "bytes": 8303,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/contact_icon.png",
    "bytes": 5159,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/contact_plate.png",
    "bytes": 79708,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/contact_text.png",
    "bytes": 8369,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/continue_icon.png",
    "bytes": 3811,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/continue_plate.png",
    "bytes": 62014,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/continue_text.png",
    "bytes": 7567,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/new_run_icon.png",
    "bytes": 3851,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/new_run_plate.png",
    "bytes": 99384,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/new_run_text.png",
    "bytes": 7897,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/settings_icon.png",
    "bytes": 5264,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/settings_plate.png",
    "bytes": 100270,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/default/settings_text.png",
    "bytes": 8681,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/admin_plate.png",
    "bytes": 141409,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/admin.png",
    "bytes": 261571,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/codex_plate.png",
    "bytes": 159723,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/codex.png",
    "bytes": 262804,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/contact_plate.png",
    "bytes": 124836,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/contact.png",
    "bytes": 241618,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/continue_plate.png",
    "bytes": 157963,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/continue.png",
    "bytes": 265351,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/gold_border.png",
    "bytes": 36969,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/new_run_plate.png",
    "bytes": 181338,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/new_run.png",
    "bytes": 280154,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/settings_plate.png",
    "bytes": 169209,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/settings.png",
    "bytes": 262979,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/hover/text_backplate.png",
    "bytes": 5191,
    "stage": "static"
  },
  {
    "path": "/assets/main_menu/v2/title_text.png",
    "bytes": 4238,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/boss_lamp_complete.png",
    "bytes": 3742,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/boss_lamp_pending.png",
    "bytes": 3286,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/boss_progress_plate.png",
    "bytes": 5394,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/right_divider.png",
    "bytes": 336,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/route_frame.png",
    "bytes": 115234,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/route_hint_icon.png",
    "bytes": 2151,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/route_hint_panel.png",
    "bytes": 3219,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/route_title_divider.png",
    "bytes": 2783,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/stat_energy.png",
    "bytes": 23536,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/stat_floor.png",
    "bytes": 22660,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/stat_gold.png",
    "bytes": 24263,
    "stage": "static"
  },
  {
    "path": "/assets/map/v2/stat_hp.png",
    "bytes": 26259,
    "stage": "static"
  },
  {
    "path": "/assets/cards_enemy/100.webp",
    "bytes": 1363382,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/101.webp",
    "bytes": 1571212,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/102.webp",
    "bytes": 2211994,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/103.webp",
    "bytes": 2508206,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/104.webp",
    "bytes": 1769350,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/79.webp",
    "bytes": 1648112,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/80.webp",
    "bytes": 2078244,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/83.webp",
    "bytes": 1976154,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/84.webp",
    "bytes": 2340648,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/89.webp",
    "bytes": 2323258,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/90.webp",
    "bytes": 1729196,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/91.webp",
    "bytes": 1967024,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/92.webp",
    "bytes": 1808174,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/93.webp",
    "bytes": 1415214,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/94.webp",
    "bytes": 1781476,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/95.webp",
    "bytes": 2666034,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/96.webp",
    "bytes": 1674596,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/97.webp",
    "bytes": 3568826,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/98.webp",
    "bytes": 1644176,
    "stage": "gif"
  },
  {
    "path": "/assets/cards_enemy/99.webp",
    "bytes": 2624920,
    "stage": "gif"
  }
];

export const TOTAL_RUNTIME_ASSET_BYTES = 61210106;
