// This file is auto-generated by game/scripts/generateAssetManifest.mjs
// Do not edit manually. Re-run `npm run assets:manifest` after asset changes.

export type RuntimeAssetManifestEntry = {
  path: string;
  bytes: number;
};

export const RUNTIME_ASSET_MANIFEST: RuntimeAssetManifestEntry[] = [
  {
    "path": "/assets/author_qr/ren-xuanqi-placeholder.svg",
    "bytes": 2950
  },
  {
    "path": "/assets/author_qr/ren-xuanqi.jpg",
    "bytes": 117281
  },
  {
    "path": "/assets/author_qr/wang-yi-placeholder.svg",
    "bytes": 2777
  },
  {
    "path": "/assets/author_qr/wang-yi.jpg",
    "bytes": 165234
  },
  {
    "path": "/assets/background_combat_act1.png",
    "bytes": 348718
  },
  {
    "path": "/assets/background_combat_act2.png",
    "bytes": 367700
  },
  {
    "path": "/assets/background_combat_act3.png",
    "bytes": 308520
  },
  {
    "path": "/assets/background_main_menu.png",
    "bytes": 81846
  },
  {
    "path": "/assets/background_map.png",
    "bytes": 8545
  },
  {
    "path": "/assets/cards_enemy/100-poster.png",
    "bytes": 146869
  },
  {
    "path": "/assets/cards_enemy/100.gif",
    "bytes": 7490346
  },
  {
    "path": "/assets/cards_enemy/100.png",
    "bytes": 83343
  },
  {
    "path": "/assets/cards_enemy/101-poster.png",
    "bytes": 104461
  },
  {
    "path": "/assets/cards_enemy/101.gif",
    "bytes": 7500045
  },
  {
    "path": "/assets/cards_enemy/101.png",
    "bytes": 66065
  },
  {
    "path": "/assets/cards_enemy/102-poster.png",
    "bytes": 159885
  },
  {
    "path": "/assets/cards_enemy/102.gif",
    "bytes": 6571275
  },
  {
    "path": "/assets/cards_enemy/102.png",
    "bytes": 96977
  },
  {
    "path": "/assets/cards_enemy/103-poster.png",
    "bytes": 156922
  },
  {
    "path": "/assets/cards_enemy/103.gif",
    "bytes": 7464473
  },
  {
    "path": "/assets/cards_enemy/103.png",
    "bytes": 96680
  },
  {
    "path": "/assets/cards_enemy/104-poster.png",
    "bytes": 160588
  },
  {
    "path": "/assets/cards_enemy/104.gif",
    "bytes": 7104281
  },
  {
    "path": "/assets/cards_enemy/76.png",
    "bytes": 3286
  },
  {
    "path": "/assets/cards_enemy/77.png",
    "bytes": 3378
  },
  {
    "path": "/assets/cards_enemy/78.png",
    "bytes": 3838
  },
  {
    "path": "/assets/cards_enemy/79-poster.png",
    "bytes": 151738
  },
  {
    "path": "/assets/cards_enemy/79.gif",
    "bytes": 6211648
  },
  {
    "path": "/assets/cards_enemy/79.png",
    "bytes": 82734
  },
  {
    "path": "/assets/cards_enemy/80-poster.png",
    "bytes": 113281
  },
  {
    "path": "/assets/cards_enemy/80.gif",
    "bytes": 7030623
  },
  {
    "path": "/assets/cards_enemy/80.png",
    "bytes": 75091
  },
  {
    "path": "/assets/cards_enemy/81.png",
    "bytes": 3670
  },
  {
    "path": "/assets/cards_enemy/82.png",
    "bytes": 3858
  },
  {
    "path": "/assets/cards_enemy/83-poster.png",
    "bytes": 131397
  },
  {
    "path": "/assets/cards_enemy/83.gif",
    "bytes": 7732330
  },
  {
    "path": "/assets/cards_enemy/83.png",
    "bytes": 90921
  },
  {
    "path": "/assets/cards_enemy/84-poster.png",
    "bytes": 148584
  },
  {
    "path": "/assets/cards_enemy/84.gif",
    "bytes": 7909742
  },
  {
    "path": "/assets/cards_enemy/84.png",
    "bytes": 104867
  },
  {
    "path": "/assets/cards_enemy/85.png",
    "bytes": 3519
  },
  {
    "path": "/assets/cards_enemy/89-poster.png",
    "bytes": 153443
  },
  {
    "path": "/assets/cards_enemy/89.gif",
    "bytes": 6477528
  },
  {
    "path": "/assets/cards_enemy/89.png",
    "bytes": 99687
  },
  {
    "path": "/assets/cards_enemy/90-poster.png",
    "bytes": 139206
  },
  {
    "path": "/assets/cards_enemy/90.gif",
    "bytes": 6338620
  },
  {
    "path": "/assets/cards_enemy/90.png",
    "bytes": 79130
  },
  {
    "path": "/assets/cards_enemy/91-poster.png",
    "bytes": 102629
  },
  {
    "path": "/assets/cards_enemy/91.gif",
    "bytes": 5509004
  },
  {
    "path": "/assets/cards_enemy/91.png",
    "bytes": 86023
  },
  {
    "path": "/assets/cards_enemy/92-poster.png",
    "bytes": 190516
  },
  {
    "path": "/assets/cards_enemy/92.gif",
    "bytes": 7609041
  },
  {
    "path": "/assets/cards_enemy/92.png",
    "bytes": 112264
  },
  {
    "path": "/assets/cards_enemy/93-poster.png",
    "bytes": 128220
  },
  {
    "path": "/assets/cards_enemy/93.gif",
    "bytes": 7296541
  },
  {
    "path": "/assets/cards_enemy/93.png",
    "bytes": 74927
  },
  {
    "path": "/assets/cards_enemy/94-poster.png",
    "bytes": 145456
  },
  {
    "path": "/assets/cards_enemy/94.gif",
    "bytes": 7595132
  },
  {
    "path": "/assets/cards_enemy/94.png",
    "bytes": 92809
  },
  {
    "path": "/assets/cards_enemy/95-poster.png",
    "bytes": 198463
  },
  {
    "path": "/assets/cards_enemy/95.gif",
    "bytes": 7565553
  },
  {
    "path": "/assets/cards_enemy/95.png",
    "bytes": 127450
  },
  {
    "path": "/assets/cards_enemy/96-poster.png",
    "bytes": 139865
  },
  {
    "path": "/assets/cards_enemy/96.gif",
    "bytes": 7723379
  },
  {
    "path": "/assets/cards_enemy/96.png",
    "bytes": 87558
  },
  {
    "path": "/assets/cards_enemy/97-poster.png",
    "bytes": 196806
  },
  {
    "path": "/assets/cards_enemy/97.gif",
    "bytes": 7487919
  },
  {
    "path": "/assets/cards_enemy/97.png",
    "bytes": 122609
  },
  {
    "path": "/assets/cards_enemy/98-poster.png",
    "bytes": 125010
  },
  {
    "path": "/assets/cards_enemy/98.gif",
    "bytes": 7792533
  },
  {
    "path": "/assets/cards_enemy/98.png",
    "bytes": 71020
  },
  {
    "path": "/assets/cards_enemy/99-poster.png",
    "bytes": 159724
  },
  {
    "path": "/assets/cards_enemy/99.gif",
    "bytes": 7511146
  },
  {
    "path": "/assets/cards_enemy/99.png",
    "bytes": 103079
  },
  {
    "path": "/assets/cards_player/1.png",
    "bytes": 72368
  },
  {
    "path": "/assets/cards_player/10.png",
    "bytes": 64048
  },
  {
    "path": "/assets/cards_player/11.png",
    "bytes": 48403
  },
  {
    "path": "/assets/cards_player/12.png",
    "bytes": 57877
  },
  {
    "path": "/assets/cards_player/13.png",
    "bytes": 68960
  },
  {
    "path": "/assets/cards_player/14.png",
    "bytes": 73522
  },
  {
    "path": "/assets/cards_player/15.png",
    "bytes": 81012
  },
  {
    "path": "/assets/cards_player/16.png",
    "bytes": 49231
  },
  {
    "path": "/assets/cards_player/17.png",
    "bytes": 41119
  },
  {
    "path": "/assets/cards_player/18.png",
    "bytes": 36893
  },
  {
    "path": "/assets/cards_player/19.png",
    "bytes": 68169
  },
  {
    "path": "/assets/cards_player/2.png",
    "bytes": 43278
  },
  {
    "path": "/assets/cards_player/20.png",
    "bytes": 87465
  },
  {
    "path": "/assets/cards_player/21.png",
    "bytes": 61805
  },
  {
    "path": "/assets/cards_player/22.png",
    "bytes": 76202
  },
  {
    "path": "/assets/cards_player/23.png",
    "bytes": 50541
  },
  {
    "path": "/assets/cards_player/24.png",
    "bytes": 21909
  },
  {
    "path": "/assets/cards_player/25.png",
    "bytes": 27307
  },
  {
    "path": "/assets/cards_player/26.png",
    "bytes": 49625
  },
  {
    "path": "/assets/cards_player/27.png",
    "bytes": 75995
  },
  {
    "path": "/assets/cards_player/28.png",
    "bytes": 24993
  },
  {
    "path": "/assets/cards_player/29.png",
    "bytes": 76187
  },
  {
    "path": "/assets/cards_player/3.png",
    "bytes": 48239
  },
  {
    "path": "/assets/cards_player/30.png",
    "bytes": 56826
  },
  {
    "path": "/assets/cards_player/31.png",
    "bytes": 70217
  },
  {
    "path": "/assets/cards_player/32.png",
    "bytes": 58766
  },
  {
    "path": "/assets/cards_player/33.png",
    "bytes": 67079
  },
  {
    "path": "/assets/cards_player/34.png",
    "bytes": 56756
  },
  {
    "path": "/assets/cards_player/35.png",
    "bytes": 62556
  },
  {
    "path": "/assets/cards_player/36.png",
    "bytes": 71566
  },
  {
    "path": "/assets/cards_player/37.png",
    "bytes": 52899
  },
  {
    "path": "/assets/cards_player/38.png",
    "bytes": 55578
  },
  {
    "path": "/assets/cards_player/39.png",
    "bytes": 51270
  },
  {
    "path": "/assets/cards_player/4.png",
    "bytes": 28694
  },
  {
    "path": "/assets/cards_player/40.png",
    "bytes": 63799
  },
  {
    "path": "/assets/cards_player/41.png",
    "bytes": 52511
  },
  {
    "path": "/assets/cards_player/42.png",
    "bytes": 52988
  },
  {
    "path": "/assets/cards_player/43.png",
    "bytes": 50137
  },
  {
    "path": "/assets/cards_player/44.png",
    "bytes": 50074
  },
  {
    "path": "/assets/cards_player/45.png",
    "bytes": 45374
  },
  {
    "path": "/assets/cards_player/46.png",
    "bytes": 58740
  },
  {
    "path": "/assets/cards_player/47.png",
    "bytes": 71450
  },
  {
    "path": "/assets/cards_player/48.png",
    "bytes": 48131
  },
  {
    "path": "/assets/cards_player/49.png",
    "bytes": 71270
  },
  {
    "path": "/assets/cards_player/5.png",
    "bytes": 63539
  },
  {
    "path": "/assets/cards_player/50.png",
    "bytes": 76721
  },
  {
    "path": "/assets/cards_player/51.png",
    "bytes": 68797
  },
  {
    "path": "/assets/cards_player/52.png",
    "bytes": 75537
  },
  {
    "path": "/assets/cards_player/53.png",
    "bytes": 71560
  },
  {
    "path": "/assets/cards_player/54.png",
    "bytes": 104598
  },
  {
    "path": "/assets/cards_player/55.png",
    "bytes": 71595
  },
  {
    "path": "/assets/cards_player/56.png",
    "bytes": 79559
  },
  {
    "path": "/assets/cards_player/57.png",
    "bytes": 66737
  },
  {
    "path": "/assets/cards_player/58.png",
    "bytes": 64495
  },
  {
    "path": "/assets/cards_player/59.png",
    "bytes": 80979
  },
  {
    "path": "/assets/cards_player/6.png",
    "bytes": 32455
  },
  {
    "path": "/assets/cards_player/60.png",
    "bytes": 67963
  },
  {
    "path": "/assets/cards_player/61.png",
    "bytes": 67731
  },
  {
    "path": "/assets/cards_player/62.png",
    "bytes": 81541
  },
  {
    "path": "/assets/cards_player/63.png",
    "bytes": 88980
  },
  {
    "path": "/assets/cards_player/64.png",
    "bytes": 81193
  },
  {
    "path": "/assets/cards_player/65.png",
    "bytes": 68886
  },
  {
    "path": "/assets/cards_player/66.png",
    "bytes": 39368
  },
  {
    "path": "/assets/cards_player/67.png",
    "bytes": 53858
  },
  {
    "path": "/assets/cards_player/68.png",
    "bytes": 46293
  },
  {
    "path": "/assets/cards_player/69.png",
    "bytes": 37176
  },
  {
    "path": "/assets/cards_player/7.png",
    "bytes": 35730
  },
  {
    "path": "/assets/cards_player/70.png",
    "bytes": 43682
  },
  {
    "path": "/assets/cards_player/71.png",
    "bytes": 44010
  },
  {
    "path": "/assets/cards_player/72.png",
    "bytes": 33091
  },
  {
    "path": "/assets/cards_player/73.png",
    "bytes": 46192
  },
  {
    "path": "/assets/cards_player/74.png",
    "bytes": 35503
  },
  {
    "path": "/assets/cards_player/75.png",
    "bytes": 50471
  },
  {
    "path": "/assets/cards_player/76.png",
    "bytes": 92809
  },
  {
    "path": "/assets/cards_player/77.png",
    "bytes": 103079
  },
  {
    "path": "/assets/cards_player/78.png",
    "bytes": 74927
  },
  {
    "path": "/assets/cards_player/79.png",
    "bytes": 82734
  },
  {
    "path": "/assets/cards_player/8.png",
    "bytes": 50588
  },
  {
    "path": "/assets/cards_player/80.png",
    "bytes": 75091
  },
  {
    "path": "/assets/cards_player/81.png",
    "bytes": 127450
  },
  {
    "path": "/assets/cards_player/82.png",
    "bytes": 122609
  },
  {
    "path": "/assets/cards_player/83.png",
    "bytes": 90921
  },
  {
    "path": "/assets/cards_player/84.png",
    "bytes": 104867
  },
  {
    "path": "/assets/cards_player/85.png",
    "bytes": 66065
  },
  {
    "path": "/assets/cards_player/9.png",
    "bytes": 62975
  },
  {
    "path": "/assets/cards_special/86.png",
    "bytes": 124450
  },
  {
    "path": "/assets/cards_special/87.png",
    "bytes": 158451
  },
  {
    "path": "/assets/cards_special/88.png",
    "bytes": 161825
  },
  {
    "path": "/assets/constitutions/balanced.png",
    "bytes": 295263
  },
  {
    "path": "/assets/constitutions/qi_deficiency.png",
    "bytes": 312807
  },
  {
    "path": "/assets/constitutions/yin_deficiency.png",
    "bytes": 317174
  }
];

export const TOTAL_RUNTIME_ASSET_BYTES = 156756730;
