import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const assetRoot = path.join(projectRoot, 'public', 'assets');
const outputPath = path.join(projectRoot, 'src', 'data', 'runtimeAssetManifest.ts');
const IMAGE_EXTENSIONS = new Set(['.png', '.gif', '.jpg', '.jpeg', '.webp', '.svg']);
const ANIMATED_ASSET_PATTERN = /^\/assets\/cards_enemy\/(?![^/]*-poster)[^/]+\.webp$/i;
const CRITICAL_ASSET_PATHS = new Set([
  '/assets/background_main_menu.png',
  '/assets/constitutions/balanced.webp',
  '/assets/constitutions/yin_deficiency.webp',
  '/assets/constitutions/qi_deficiency.webp',
]);

const toPosixPath = (value) => value.split(path.sep).join('/');

const isExcludedRuntimeAsset = (assetPath) =>
  assetPath.startsWith('/assets/main_menu/v2/qa/') ||
  /^\/assets\/main_menu\/reference(?:_hover)?\.png$/i.test(assetPath);

const walk = (dirPath) => {
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...walk(fullPath));
      continue;
    }

    if (!entry.isFile()) {
      continue;
    }

    if (!IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      continue;
    }

    files.push(fullPath);
  }

  return files;
};

const getAssetStage = (assetPath) => {
  if (CRITICAL_ASSET_PATHS.has(assetPath)) {
    return 'critical';
  }
  if (assetPath.toLowerCase().endsWith('.gif') || ANIMATED_ASSET_PATTERN.test(assetPath)) {
    return 'gif';
  }
  return 'static';
};

const assetFiles = walk(assetRoot)
  .map((fullPath) => {
    const relativePath = toPosixPath(path.relative(path.join(projectRoot, 'public'), fullPath));
    const assetPath = `/${relativePath}`;
    const fileSize = fs.statSync(fullPath).size;

    return {
      path: assetPath,
      bytes: fileSize,
      stage: getAssetStage(assetPath),
    };
  })
  .filter((entry) => !isExcludedRuntimeAsset(entry.path))
  .sort((left, right) => {
    const stageOrder = { critical: 0, static: 1, gif: 2 };
    if (left.stage !== right.stage) return stageOrder[left.stage] - stageOrder[right.stage];
    if (left.stage === 'static' && right.stage === 'static') {
      const leftBg = left.path.startsWith('/assets/background_combat');
      const rightBg = right.path.startsWith('/assets/background_combat');
      if (leftBg !== rightBg) return leftBg ? 1 : -1;
    }
    return left.path.localeCompare(right.path, 'en');
  });

const totalBytes = assetFiles.reduce((sum, entry) => sum + entry.bytes, 0);

const fileContents = `// This file is auto-generated by game/scripts/generateAssetManifest.mjs
// Do not edit manually. Re-run \`npm run assets:manifest\` after asset changes.

export type RuntimeAssetStage = 'critical' | 'static' | 'gif';

export type RuntimeAssetManifestEntry = {
  path: string;
  bytes: number;
  stage: RuntimeAssetStage;
};

export const RUNTIME_ASSET_MANIFEST: RuntimeAssetManifestEntry[] = ${JSON.stringify(assetFiles, null, 2)};

export const TOTAL_RUNTIME_ASSET_BYTES = ${totalBytes};
`;

fs.writeFileSync(outputPath, fileContents, 'utf8');

console.log(
  JSON.stringify(
    {
      generated: outputPath,
      assetCount: assetFiles.length,
      totalBytes,
    },
    null,
    2,
  ),
);
