import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const assetRoot = path.join(projectRoot, 'public', 'assets');
const outputPath = path.join(projectRoot, 'src', 'data', 'runtimeAssetManifest.ts');
const IMAGE_EXTENSIONS = new Set(['.png', '.gif', '.jpg', '.jpeg', '.webp', '.svg']);

const toPosixPath = (value) => value.split(path.sep).join('/');

const walk = (dirPath) => {
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...walk(fullPath));
      continue;
    }

    if (!entry.isFile()) {
      continue;
    }

    if (!IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      continue;
    }

    files.push(fullPath);
  }

  return files;
};

const assetFiles = walk(assetRoot)
  .map((fullPath) => {
    const relativePath = toPosixPath(path.relative(path.join(projectRoot, 'public'), fullPath));
    const fileSize = fs.statSync(fullPath).size;
    return {
      path: `/${relativePath}`,
      bytes: fileSize,
    };
  })
  .sort((left, right) => left.path.localeCompare(right.path, 'en'));

const totalBytes = assetFiles.reduce((sum, entry) => sum + entry.bytes, 0);

const fileContents = `// This file is auto-generated by game/scripts/generateAssetManifest.mjs
// Do not edit manually. Re-run \`npm run assets:manifest\` after asset changes.

export type RuntimeAssetManifestEntry = {
  path: string;
  bytes: number;
};

export const RUNTIME_ASSET_MANIFEST: RuntimeAssetManifestEntry[] = ${JSON.stringify(assetFiles, null, 2)};

export const TOTAL_RUNTIME_ASSET_BYTES = ${totalBytes};
`;

fs.writeFileSync(outputPath, fileContents, 'utf8');

console.log(
  JSON.stringify(
    {
      generated: outputPath,
      assetCount: assetFiles.length,
      totalBytes,
    },
    null,
    2,
  ),
);
